### PR TITLE
fixed undefined context bug and implemented language setting

### PR DESCRIPTION
**Pull request by gaperlinski**
Hi, I've implemented being able to set up locale as per [this request ](https://github.com/anarchicknight/nativescript-texttospeech/issues/2). I've also fixed a bug on Android where the context would be undefined and the tts object wouldn't be constructed.

### CODE REVIEW

**Comment by anarchicknight** [comment]
Thanks for this.

I'm currently on holiday in Spain but will take a look when I get back in just over a week

**Comment by svzi** [comment]
Any progress on this PR? I would like to see this functionality added.

**Comment by anarchicknight** [comment]
I don't have the ability at the moment to checkout the PR and test.

Has anyone else pulled it down and made sure everything works as expected?

If anyone can confirm then I will merge it straight in

**Comment by svzi** [comment]
Sorry, I've just played around with and it looked good. But I never used the version before this PR, so I can't judge on that.

**Comment by anarchicknight** [comment]
@gaperlinski OK, based on the above I am going to look to merge this in.

I can see the README has been updated along with the code, however before I merge could you please bump the version number in package.json so I can easily checkout and npm publish.

Are users able to continue calling the speak method as they have done in their app up to now? Or is the locale parameter now required in order for the method to be called?

Just finding out whether there is a breaking change here or just a backwards compatible new feature? This will decide what version number to publish.

Breaking change please use 2.0.0 in package.json
Backwards compatible new feature please use 1.2.0

Thanks.

**Comment by apiejh** [comment]
Hi,

I've updated the version to 1.2.0. The locale parameter is optional just like the other parameters except for the first one.

Thanks

**Comment by anarchicknight** [comment]
merged - thanks all

**Pull request merged**
